import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import DashboardNavigation from "@/components/ui/dashboard-navigation";
import MobileDashboardNavigation from "@/components/ui/mobile-dashboard-navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Karaokebox Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="flex flex-col md:flex-row">
        <div className="hidden md:block md:max-w-[400px]">
          <DashboardNavigation />
        </div>
        <div className="md:hidden">
          <MobileDashboardNavigation />
        </div>
        <main className="p-8">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
